const SAN_CURRENT='c21106f9-3ef5-4f3a-8604-f992b4db7512',SAN_HISTORY='c22b1ef2-dcf8-4d77-be1a-ee3638092aab';
export const CITIES=[
 {id:'austin',name:'Austin',coverage:'Live issued permits',searchable:true,badge:'Live public feed',description:'Issued construction permits from the City of Austin open-data portal.',source:'City of Austin · Issued Construction Permits',official:'https://data.austintexas.gov/Building-and-Development/Issued-Construction-Permits/3syk-w9eu',api:'https://data.austintexas.gov/resource/3syk-w9eu.json'},
 {id:'san-antonio',name:'San Antonio',coverage:'Live issued permits',searchable:true,badge:'Live public feed',description:'Current and 2020–2024 issued permits from the City of San Antonio open-data portal.',source:'City of San Antonio · Building Permits',official:'https://data.sanantonio.gov/dataset/building-permits'},
 {id:'dallas',name:'Dallas',coverage:'Historical search',searchable:true,badge:'Historical only',description:'The public dataset is historical and no longer updated. Current records belong in Dallas Accela.',source:'City of Dallas · Building Permits (historical)',official:'https://aca-prod.accela.com/DALLASTX/Login.aspx',dataset:'https://www.dallasopendata.com/Services/Building-Permits/e7gq-4sah',api:'https://www.dallasopendata.com/resource/e7gq-4sah.json'},
 {id:'houston',name:'Houston',coverage:'Current weekly report',searchable:true,badge:'Partial current feed',description:'Search the City of Houston weekly Permit Activity Report inside PermitTap.',source:'City of Houston · Permit Activity Report',official:'https://www.houstonpermittingcenter.org/sold-permits-search'}];
export const CITY_BY_ID=Object.fromEntries(CITIES.map(c=>[c.id,c]));
const clean=q=>q.trim().replace(/\s+/g,' ').slice(0,100),lit=q=>clean(q).replaceAll("'","''"),valid=v=>v&&String(v).toUpperCase()!=='NULL'?v:null;
export function buildQuery(city,q,mode){const value=lit(q),u=new URL(city.api);u.searchParams.set('$limit','50');if(city.id==='austin'){u.searchParams.set('$select','permit_number,permit_type_desc,work_class,original_address1,original_city,original_zip,description,applieddate,issue_date,status_current,statusdate,expiresdate,completed_date,total_job_valuation,link');u.searchParams.set('$where',mode==='permit'?`upper(permit_number) like upper('%${value}%')`:`upper(original_address1) like upper('%${value}%')`);u.searchParams.set('$order','issue_date DESC')}else{u.searchParams.set('$select','permit_number,permit_type,issued_date,value,work_description,land_use,street_address,zip_code');u.searchParams.set('$where',mode==='permit'?`upper(permit_number) like upper('%${value}%')`:`upper(street_address) like upper('%${value}%')`)}return u}
export function buildSanAntonioUrl(resource,q,mode,suggest=false){const field=mode==='permit'?'PERMIT #':'ADDRESS',value=lit(q),select=suggest?`DISTINCT "ADDRESS"`:'"PERMIT TYPE","PERMIT #","PROJECT NAME","WORK TYPE","ADDRESS","DATE SUBMITTED","DATE ISSUED","DECLARED VALUATION"',wild=suggest?`${value}%`:`%${value}%`,sql=`SELECT ${select} FROM "${resource}" WHERE upper("${field}") LIKE upper('${wild}') ${suggest?'':'ORDER BY "DATE ISSUED" DESC'} LIMIT ${suggest?8:50}`,u=new URL('https://data.sanantonio.gov/api/3/action/datastore_search_sql');u.searchParams.set('sql',sql);return u}
async function json(url,signal){const r=await fetch(url,{signal});if(!r.ok)throw new Error(`Source returned ${r.status}`);return r.json()}
export async function searchPermits({city,query,mode,signal}){let records=[];if(city.id==='san-antonio'){const parts=await Promise.all([SAN_CURRENT,SAN_HISTORY].map(id=>json(buildSanAntonioUrl(id,query,mode),signal)));records=parts.flatMap(x=>x.result.records.map(normalizeSan)).sort((a,b)=>String(b.issued).localeCompare(String(a.issued))).slice(0,50)}else if(city.id==='houston'){const data=await json(new URL('../data/houston.json?v=4',import.meta.url),signal),needle=clean(query).toUpperCase();records=data.records.filter(x=>String(mode==='permit'?x.number:x.address).toUpperCase().includes(needle)).slice(0,50).map(x=>({...x,status:'Published in weekly report',link:data.source}))}else{const rows=await json(buildQuery(city,query,mode),signal);records=rows.map(x=>normalizeSocrata(city,x))}return{records,truncated:records.length===50,fetchedAt:new Date().toISOString()}}
export async function suggestAddresses({city,query,signal}){if(clean(query).length<3)return[];if(city.id==='san-antonio'){const parts=await Promise.all([SAN_CURRENT,SAN_HISTORY].map(id=>json(buildSanAntonioUrl(id,query,'address',true),signal)));return[...new Set(parts.flatMap(x=>x.result.records.map(r=>r.ADDRESS)).filter(Boolean))].slice(0,8)}if(city.id==='houston'){const data=await json(new URL('../data/houston.json?v=4',import.meta.url),signal),needle=clean(query).toUpperCase(),all=[...new Set(data.records.map(x=>x.address))];return all.filter(x=>x.toUpperCase().startsWith(needle)).concat(all.filter(x=>!x.toUpperCase().startsWith(needle)&&x.toUpperCase().includes(needle))).slice(0,8)}const field=city.id==='austin'?'original_address1':'street_address',value=lit(query),u=new URL(city.api);u.searchParams.set('$select',`${field},count(*) as permit_count`);u.searchParams.set('$where',`upper(${field}) like upper('${value}%')`);u.searchParams.set('$group',field);u.searchParams.set('$order','permit_count DESC');u.searchParams.set('$limit','8');return(await json(u,signal)).map(x=>x[field]).filter(Boolean)}
function normalizeSan(x){return{number:x['PERMIT #'],type:x['PERMIT TYPE'],address:x.ADDRESS,description:[valid(x['PROJECT NAME']),valid(x['WORK TYPE'])].filter(Boolean).join(' · '),status:'Issued permit',issued:x['DATE ISSUED'],value:valid(x['DECLARED VALUATION']),link:'https://data.sanantonio.gov/dataset/building-permits'}}
function normalizeSocrata(city,x){return city.id==='austin'?{number:x.permit_number,type:x.permit_type_desc||x.work_class,address:[x.original_address1,x.original_city,x.original_zip].filter(Boolean).join(', '),description:x.description,status:x.status_current,issued:x.issue_date,completed:x.completed_date,expires:x.expiresdate,value:x.total_job_valuation,link:x.link?.url||x.link||city.official}:{number:x.permit_number,type:x.permit_type,address:[x.street_address,x.zip_code].filter(Boolean).join(', '),description:x.work_description||x.land_use,status:'Historical record',issued:x.issued_date,value:x.value,link:city.dataset}}
