export const CITIES=[
 {id:'austin',name:'Austin',coverage:'Searchable',searchable:true,badge:'Supported public feed',description:'Issued construction permits from the City of Austin open-data portal.',source:'City of Austin · Issued Construction Permits',official:'https://data.austintexas.gov/Building-and-Development/Issued-Construction-Permits/3syk-w9eu',api:'https://data.austintexas.gov/resource/3syk-w9eu.json'},
 {id:'san-antonio',name:'San Antonio',coverage:'Official lookup',searchable:false,badge:'Official portal',description:'Building applications, issued permits, and trade-work reports are available through Open Data SA.',source:'City of San Antonio · Development Services Reports',official:'https://www.sa.gov/Directory/Departments/DSD/About/Reports'},
 {id:'dallas',name:'Dallas',coverage:'Historical search',searchable:true,badge:'Historical only',description:'The public dataset is historical and no longer updated. Current records belong in Dallas Accela.',source:'City of Dallas · Building Permits (historical)',official:'https://aca-prod.accela.com/DALLASTX/Login.aspx',dataset:'https://www.dallasopendata.com/Services/Building-Permits/e7gq-4sah',api:'https://www.dallasopendata.com/resource/e7gq-4sah.json'},
 {id:'houston',name:'Houston',coverage:'Official lookup',searchable:false,badge:'Rolling 3 years',description:'The official sold-permit search covers a rolling three-year period.',source:'Houston Permitting Center · Sold Permits',official:'https://www.houstonpermittingcenter.org/sold-permits-search'}];
export const CITY_BY_ID=Object.fromEntries(CITIES.map(c=>[c.id,c]));
const clean=q=>q.trim().replace(/\s+/g,' ').slice(0,100); const lit=q=>clean(q).replaceAll("'","''");
export function buildQuery(city,q,mode){const value=lit(q);const u=new URL(city.api);u.searchParams.set('$limit','50');if(city.id==='austin'){u.searchParams.set('$select','permit_number,permit_type_desc,work_class,original_address1,original_city,original_zip,description,applieddate,issue_date,status_current,statusdate,expiresdate,completed_date,total_job_valuation,contractor_company_name,link');u.searchParams.set('$where',mode==='permit'?`upper(permit_number) like upper('%${value}%')`:`upper(original_address1) like upper('%${value}%')`);u.searchParams.set('$order','issue_date DESC')}else{u.searchParams.set('$select','permit_number,permit_type,issued_date,contractor,value,work_description,land_use,street_address,zip_code');u.searchParams.set('$where',mode==='permit'?`upper(permit_number) like upper('%${value}%')`:`upper(street_address) like upper('%${value}%')`)}return u}
export async function searchPermits({city,query,mode,signal}){if(!city.searchable)throw new Error('official-only');const r=await fetch(buildQuery(city,query,mode),{signal});if(!r.ok)throw new Error(`Source returned ${r.status}`);const rows=await r.json();return{records:rows.map(x=>normalize(city,x)),truncated:rows.length===50,fetchedAt:new Date().toISOString()}}
export async function suggestAddresses({city,query,signal}){if(!city.searchable||clean(query).length<3)return[];const field=city.id==='austin'?'original_address1':'street_address',value=lit(query),u=new URL(city.api);u.searchParams.set('$select',`${field},count(*) as permit_count`);u.searchParams.set('$where',`upper(${field}) like upper('${value}%')`);u.searchParams.set('$group',field);u.searchParams.set('$order','permit_count DESC');u.searchParams.set('$limit','8');const r=await fetch(u,{signal});if(!r.ok)throw new Error('suggestions unavailable');const rows=await r.json();return rows.map(x=>x[field]).filter(Boolean)}
function normalize(city,x){return city.id==='austin'?{number:x.permit_number,type:x.permit_type_desc||x.work_class,address:[x.original_address1,x.original_city,x.original_zip].filter(Boolean).join(', '),description:x.description,status:x.status_current,issued:x.issue_date,completed:x.completed_date,expires:x.expiresdate,value:x.total_job_valuation,contractor:x.contractor_company_name,link:x.link?.url||x.link||city.official}:{number:x.permit_number,type:x.permit_type,address:[x.street_address,x.zip_code].filter(Boolean).join(', '),description:x.work_description||x.land_use,status:'Historical record',issued:x.issued_date,value:x.value,contractor:x.contractor,link:city.dataset}}
